app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password) :
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

class Post(db.Model):

    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    body = db.Column(db.Text)
    date = db.Column(db.String)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    category = db.Column(db.String)
    comments = db.relationship("Comment", backref = "comment", lazy = "dynamic")

    def save_post(self):
        '''
        Function to save a new pitch
        '''
        db.session.add(self)
        db.session.commit()

    def get_post_comments(self):
        post = Post.query.filter_by(id = self.id).first()
        comments = Comment.query.filter_by(id = post.id)
        
        return comments
    

class Comment(db.Model):
     
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    body = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id"))


    def save_comment(self):
        db.session.add(self)
        db.session.commit()   

        
        
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError,SelectField
from wtforms.validators import Required,Email
#from .models import User

class PostForm(FlaskForm):

    title = StringField('Pitch title',validators=[Required()])
    post = TextAreaField('Pitch', validators=[Required()])
    submit = SubmitField('Publish')
    category = SelectField(
        "category",
        choices=[("pick-up", "pick-up"),("boring","boring"),("funny","funny"),("promotion","promotion"),("product","product"),("cheesy","cheesy"),("random","random")],validators = [Required()]
    )
   

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
   
    body = TextAreaField('comment', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)

    mail.init_app(app)

    # Will add the views and forms
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # setting config
    return app
    

   

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Post,Comment
from .forms import PostForm,CommentForm,UpdateProfile
from .. import db,photos
from flask_login import login_user, logout_user, login_required, current_user
import datetime


@main.route('/')
def index():
    """View root page function that returns index page and the various news sources"""

    title = 'Home- Welcome to Pitches'
    form = PostForm()
    return render_template('index.html', form=form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)



@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html')

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/post/<category>')
def post(category):
    
    posts= None
    if category == 'all':
        posts = Post.query.order_by(Post.date.desc())
    else :
        posts = Post.query.filter_by(category = category).order_by(Post.date.desc()).all()

    return render_template('post.html', posts = posts ,title = category.upper())

@main.route('/new/post/<uname>', methods = ['GET','POST'])
@login_required
def new_post(uname):
    form = PostForm()
    title = 'Express yourself'
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
      
    if form.validate_on_submit():
        title = form.title.data
        body = form.post.data
        category = form.category.data 
        dateNow = datetime.datetime.now()
        date = str(dateNow)
    

        add_post = Post(title = title,body=body,category=category,date=date)
        add_post.save_post()
        posts = Post.query.all()
        return redirect(url_for('main.post',category = category ))
    return render_template('new_post.html', form = form, title =title)

 

@main.route('/post/<post_id>/add/comment', methods = ['GET','POST'])
@login_required
def comment(post_id):
   
    post = Post.query.filter_by(id = post_id).first()
    form = CommentForm()
 
    if form.validate_on_submit():
        body = form.body.data
      
        new_comment = Comment(body=body)
        new_comment.save_comment()
        
        return redirect(url_for("main.show_comments",post_id = post_id))
    return render_template("comment.html", form = form, post = post)

@main.route('/<post_id>/comments')
@login_required
def show_comments(post_id):
    
    post = Post.query.filter_by(id = post_id).first()
    
    comments = post.get_post_comments()

    return render_template('show_comments.html',comments= comments,post=post)


       

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  --> 

app/templates/comment.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock%}

{% block content%}
<div class="container">
    <h3>Comment on {{post.title | upper}} by {{post.username| upper}}</h3>
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Pitchy-Pitches</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
	</head>
	<body id="top">
				<section id="banner" data-video="images/banner">
					<div class="inner">
						<header>
							<h1>Pitchy-Pitches</h1>
							<p>Welcome to Pitchy-Pitches..... remember to always express yourself and hit the home run</p>
						</header>
						{% if current_user.is_authenticated %}
						<div class="box">
								
								<div class="inner">
										<a href="{{url_for('main.profile',uname=current_user.username)}}"class="button fit">Profile</a>
								</div>
							</div>
							<div class="box">
								
									<div class="inner">
										<a href="{{url_for('auth.logout')}}"  class="button style2 fit">Sign out</a>
									</div>
								</div>
						{% else %}
						<div class="box">
								
								<div class="inner">
										<a href="{{url_for('auth.login')}}" class="button style2 fit">Sign in</a>
								</div>
							</div>
           
						{%endif%}
						<a href="#main" href="{{url_for('static',filename='photos/arrow.svg')}}"class="more">View </a>
					</div>
                </section>
                <div id="main">
					<div class="inner">

                    <!-- Boxes -->
                    <h2 class="text-center">Categories</h2>
						<div class="thumbnails">

							<div class="box">
							
								<div class="inner">
                      <a href="{{url_for('main.post',category='product')}}" class="button fit">Product</a>
								</div>
							</div>

							<div class="box">
								
								<div class="inner">
									<a href="{{url_for('main.post',category='pick-up')}}" class="button style2 fit">Pick Up Lines</a>
								</div>
							</div>

							<div class="box">
								
								<div class="inner">
                                    <a href="{{url_for('main.post',category='funny')}}" class="button style3 fit">Comedy</a>
								</div>
							</div>

							<div class="box">
								
								<div class="inner">
                                    <a href="{{url_for('main.post',category='cheesy')}}" class="button style2 fit">Cheesy</a>	
								</div>
							</div>

							<div class="box">
							
								<div class="inner">
                                    <a href="{{url_for('main.post',category='random')}}" class="button style3 fit"> Random</a>
								</div>
							</div>

							<div class="box">
								
								<div class="inner">
                                   
                                    <a href="{{url_for('main.post',category='all')}}" class="button fit">All</a>
								</div>
							</div>

						</div>

					</div>
				</div>

<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.poptrox.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/templates/macros.html
{%macro displayPosts()%}
<h3>Hello {{current_user.username}}</h3>
<div class="row">
  <div class="col-xs-6">
    {{ wtf.quick_form(form) }}
  </div>
  <div class="col-xs-6">
    {% for post in posts %}
    <li class="post">
      <div class="profile-thumbnail">
        <a href="{{ url_for('.user', username=post.author.username) }}"></a>
      </div>
      <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
      <div class="post-author">
        <a href="{{ url_for('.user', username=post.author.username) }}">
{{ post.author.username }}
</a>
      </div>
      <div class="post-body">{{ post.body }}</div>
    </li>
    {% endfor %}
  </div>
</div>
{% endmacro %}

app/templates/marcos.html
{%macro displayPosts()%}
<h3>Hello {{current_user.username}}</h3>
<div class="row">
  <div class="col-xs-6">
    {{ wtf.quick_form(form) }}
  </div>
  <div class="col-xs-6">
    {% for post in posts %}
    <li class="post">
      <div class="profile-thumbnail">
        <a href="{{ url_for('.user', username=post.author.username) }}"></a>
      </div>
      <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
      <div class="post-author">
        <a href="{{ url_for('.user', username=post.author.username) }}">
{{ post.author.username }}
</a>
      </div>
      <div class="post-body">{{ post.body }}</div>
    </li>
    {% endfor %}
  </div>
</div>
{% endmacro %}

app/templates/navbar.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">

<!-- Side Navigation -->
<div class="w3-top">
  <div class="w3-container w3-theme w3-padding" id="myHeader">
    <a href="/"><h4 class="w3-bar-item "><b><i>Pitchy-pitches</b> </h4> </a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
    </div>
  </div>
</div>

app/templates/new_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8 center">

            {{ wtf.quick_form(form) }}
        </div>

    </div>

{% endblock %}

app/templates/post.html
{% block content %}
<head>
		<title>Pitchy-Pitches</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
	</head>
	<body id="top">
				<section id="banner" data-video="images/banner">
					<div class="inner">
						<header>
							<h1>Pitchy-Pitches</h1>
							<p>Welcome to Pitchy-Pitches..... remember to always express yourself and hit the home run</p>
                        </header>
                        <div class="box">
								<div class="inner">
										<a href="/"class="button style3 fit">Home</a>
								</div>
							</div>
						{% if current_user.is_authenticated %}
						<div class="box">
								<div class="inner">
										<a href="{{url_for('main.profile',uname=current_user.username)}}"class="button fit">Profile</a>
								</div>
							</div>
							<div class="box">
									<div class="inner">
										<a href="{{url_for('auth.logout')}}"  class="button style2 fit">Sign out</a>
									</div>
								</div>
						{% else %}
						<div class="box">
								
								<div class="inner">
										<a href="{{url_for('auth.login')}}" class="button style2 fit">Sign in</a>
								</div>
							</div>
                            {%endif%}
                            {% if current_user.is_authenticated %}
                            <a href="{{url_for('main.new_post',uname = current_user.username)}}" class="button style3 fit">Pitch</a>
                         {% endif %}
                    </div>
                </section>
                            <div class="main">
                                
                                <div class="inner">

                                        <!-- Boxes -->
                                        <h2 class="text-center">{{title | upper}} PITCHES</h2>
                                            
                                                    {% if posts %}
                                                    {% for row in posts | batch(2) %}
                                                <div class="box">
                                                        {% for post in row %}
                                                    <div class="inner">
                                                            <h3>{{post.title | upper}}</h3>
                                                            <p>Poster: <a href="{{url_for('main.profile', uname = current_user.username)}}">{{current_user.username}}</a></p>

                                                            <p> Pitch: {{post.body}}</p>
                                                            <p>CATEGORY: <strong>{{post.category}}</strong></p>
                                                            <p>Date: <strong>{{post.date}}</strong> </p>
                                                    </div>
                                                    <div>
                                                    {% if current_user.is_authenticated %}
                                                    <a href="{{url_for('main.show_comments',post_id = post.id)}}" class="button fit">view comments</a>
                                                 {% endif %}
                                                </div>
                                                </div>
                                         
                                    </div>
 
  
  
                                
                                           
                                        </div>
                                        {% endfor %}
                                    </div> 
                                    {% endfor %}
                                {
                                {% endif %}
                            </div>
{% endblock %}

app/templates/profile/profile.html
{% block content %}
<head>
		<title>Pitchy-Pitches</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
	</head>
	<body id="top">
				<section id="banner" data-video="images/banner">
					<div class="inner">
						<header>
							<h1>Pitchy-Pitches</h1>
							<p>Welcome to Pitchy-Pitches..... remember to always express yourself and hit the home run</p>
                        </header>
                        
            {% if current_user.is_authenticated %}
            <h3> Welcome {{user.username| capitalize}}!</h3>
            <div class="box">
								<div class="inner">
										<a href="/"class="button style3 fit">Home</a>
								</div>
							</div>
					
							<div class="box">
									<div class="inner">
										<a href="{{url_for('auth.logout')}}"  class="button style2 fit">Sign out</a>
									</div>
								</div>
						{% else %}
						<div class="box">
								
								<div class="inner">
										<a href="{{url_for('auth.login')}}" class="button style2 fit">Sign in</a>
								</div>
							</div>
                      {%endif%}
                           
                    </div>
                </section>
                <div class="box">
							
                    <div class="inner">
                        <div class="col-md-4">
                            {% if user.profile_pic_path %}
                        
                            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" style="border-radius:50%; height: 15%; width: 15%,">
                        
                            {%else%}
                            <p>No profile picture</p>
                        
                            {% endif %}
                        
                                {% if user == current_user %}
                            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                        
                              <input type="file"  name="photo" class="form-control" required>
                              <input type="submit">
                            </form>
                              {% endif %}
                          </div>
                    </div>
                  </div>

                <div class="box">
							
                    <div class="inner">
                        {% if user.bio %}
                        <p> {{user.bio}}</p>
                      {%else%}
                        <p> {{user.username| capitalize}} has no bio </p>
                      {% endif %}
                      {% if user == current_user %}
                       <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
                     {% endif %}
                    </div>
                    </div>
                  

  
  <!------Update profile information---->
 

</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/show_comments.html
{% extends "base.html" %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='css/comments.css')}}">
{% endblock%}
{% block content%}
    <div class="container">
    <div class="row comment-row">
        <h3 class="comment-title">Comments for <strong>{{post.title | upper }}</strong> by <strong>{{current_user.username | upper}}</strong></h3>
        <a class="post-comment" href="{{url_for('main.comment',user = current_user.id, post_id = post.id)}}"><button class="btn btn-info mr-0">Add
                a comment</button></a>


    </div>

        {% if comments %}
            {% for comment in comments %}
            <div class="row">
                <div class="col-xs-1 col-md-1 col-lg-1">
                    
                </div>
                <div class="col">
                   
                    <p>  <strong>{{comment.time}}</strong></p>
                </div>
            </div>
            <hr>    
            {% endfor %}
        {% else %}
        <h2>There are no comments</h2>
        {% endif %}

    </div>

{% endblock %}